/*
 * FICHIER GÉNÉRÉ — ne pas modifier à la main.
 *
 * Ce que chaque app importe RÉELLEMENT du paquet, et ce qu'elle recopie encore
 * à côté. Écrit par `scripts/measure-adoption.mjs`, qui exige les dépôts des
 * apps clonés à côté de celui-ci — ce que la CI n'a pas.
 *
 * Chargé par un `<script src>` classique, comme `metrics.js` : la page ne fait
 * AUCUNE requête réseau et s'ouvre en `file://`.
 *
 * `measured: 0` = le relevé n'a jamais tourné. La vitrine n'affiche alors
 * simplement aucun taux d'adoption.
 *
 * RELEVÉ CUMULÉ. `measured` compte les apps que cet enregistrement CONNAÎT,
 * pas celles vues à la dernière exécution : chaque entrée porte son propre
 * `measuredAt`. Personne n'ayant les dix-sept dépôts clonés en permanence,
 * l'écriture fusionne au lieu de remplacer — sans quoi un relevé partiel
 * effacerait le travail des autres.
 */
globalThis.SHOWROOM_ADOPTION = {
  generatedAt: '2026-08-29T14:11:54.054Z',
  measured: 17,
  total: 17,
  apps: {
    'miss-badminton': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'clearErrorLog',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'getErrorLog',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/observability',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'applyUpdate',
          file: 'register-sw.ts',
        },
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'ConfirmDialog',
          file: 'ConfirmDialog.tsx',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'share',
          file: 'share.ts',
        },
        {
          exported: 'Sheet',
          file: 'Modal.tsx',
        },
        {
          exported: 'useI18n',
          file: 'useI18n.ts',
        },
        {
          exported: 'useOnline',
          file: 'useOnline.ts',
        },
        {
          exported: 'useTheme',
          file: 'theme.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-carbook': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'createI18n',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/i18n',
        '/react/observability',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'EmptyState',
          file: 'EmptyState.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'security',
          file: 'security.ts',
        },
        {
          exported: 'ThemeToggle',
          file: 'ThemeToggle.tsx',
        },
        {
          exported: 'Toast',
          file: 'ToastContext.tsx',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdateBanner.tsx',
        },
        {
          exported: 'useTheme',
          file: 'useTheme.ts',
        },
        {
          exported: 'webVitals',
          file: 'web-vitals.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-contraction': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'definePwaPlaywrightConfig',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-base',
        '/react',
        '/react/observability',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'AppFooter',
          file: 'AppFooter.tsx',
        },
        {
          exported: 'applyUpdate',
          file: 'register-sw.ts',
        },
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'EmptyState',
          file: 'EmptyState.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'security',
          file: 'security.ts',
        },
        {
          exported: 'useI18n',
          file: 'useI18n.ts',
        },
        {
          exported: 'useTheme',
          file: 'theme.ts',
        },
        {
          exported: 'webVitals',
          file: 'web-vitals.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-dice': {
      symbols: [],
      subpaths: [],
      duplicates: [
        {
          exported: 'applyUpdate',
          file: 'register-sw.ts',
        },
        {
          exported: 'ErrorBoundary',
          file: 'ErrorBoundary.tsx',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'share',
          file: 'share.ts',
        },
        {
          exported: 'Sheet',
          file: 'Sheet.tsx',
        },
        {
          exported: 'useI18n',
          file: 'useI18n.ts',
        },
        {
          exported: 'useTheme',
          file: 'useTheme.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-genius': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'createI18n',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/i18n',
        '/react/observability',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'AppFooter',
          file: 'AppFooter.tsx',
        },
        {
          exported: 'applyUpdate',
          file: 'forceUpdate.ts',
        },
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'Button',
          file: 'Button.tsx',
        },
        {
          exported: 'ConfirmDialog',
          file: 'ConfirmDialog.tsx',
        },
        {
          exported: 'EmptyState',
          file: 'EmptyState.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'Sheet',
          file: 'Sheet.tsx',
        },
        {
          exported: 'TextField / SelectField / TextAreaField',
          file: 'Field.tsx',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdatePrompt.tsx',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-lookhouse': {
      symbols: ['baseTestOptions'],
      subpaths: ['/vitest-base'],
      duplicates: [
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'geo',
          file: 'geo.ts',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'ThemeToggle',
          file: 'ThemeToggle.tsx',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-supaboss': {
      symbols: [
        'FamilyApps',
        'I18nPaths',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'createTranslator',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'initSentry',
        'installErrorReporter',
        'recordError',
        'useTheme',
        'useUpdatePrompt',
      ],
      subpaths: [
        '/playwright-base',
        '/react',
        '/react/i18n',
        '/react/observability',
        '/react/use-update-prompt',
        '/vite-csp',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'EmptyState',
          file: 'EmptyState.tsx',
        },
        {
          exported: 'ErrorBoundary',
          file: 'ErrorBoundary.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'Skeleton',
          file: 'Skeleton.tsx',
        },
        {
          exported: 'Toast',
          file: 'ToastViewport.tsx',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdatePrompt.tsx',
        },
        {
          exported: 'useOnline',
          file: 'useOnline.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-ticket-pwa': {
      symbols: ['baseTestOptions'],
      subpaths: ['/vitest-base'],
      duplicates: [
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'ThemeToggle',
          file: 'ThemeToggle.tsx',
        },
        {
          exported: 'useOnline',
          file: 'useOnline.ts',
        },
        {
          exported: 'useTheme',
          file: 'theme.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'miss-uwh': {
      symbols: [
        'FamilyApps',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'createTranslator',
        'cspPlugin',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-a11y',
        '/react',
        '/react/i18n',
        '/react/observability',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'AppFooter',
          file: 'AppFooter.tsx',
        },
        {
          exported: 'applyUpdate',
          file: 'forceUpdate.ts',
        },
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'Button',
          file: 'Button.tsx',
        },
        {
          exported: 'ConfirmDialog',
          file: 'ConfirmDialog.tsx',
        },
        {
          exported: 'EmptyState',
          file: 'EmptyState.tsx',
        },
        {
          exported: 'ErrorBoundary',
          file: 'ErrorBoundary.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'Sheet',
          file: 'Sheet.tsx',
        },
        {
          exported: 'TextField / SelectField / TextAreaField',
          file: 'Field.tsx',
        },
        {
          exported: 'Toast',
          file: 'ToastViewport.tsx',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdatePrompt.tsx',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-cim10': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'createI18n',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/i18n',
        '/react/observability',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'AppFooter',
          file: 'AppFooter.tsx',
        },
        {
          exported: 'applyUpdate',
          file: 'register-sw.ts',
        },
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'ThemeToggle',
          file: 'ThemeToggle.tsx',
        },
        {
          exported: 'useTheme',
          file: 'useTheme.ts',
        },
        {
          exported: 'webVitals',
          file: 'web-vitals.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-doc': {
      symbols: [
        'FamilyApps',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'useReducedMotion',
      ],
      subpaths: [
        '/react',
        '/react/i18n',
        '/react/observability',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'Badge',
          file: 'Badge.tsx',
        },
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'Button',
          file: 'Button.tsx',
        },
        {
          exported: 'ConfirmDialog',
          file: 'ConfirmDialog.tsx',
        },
        {
          exported: 'EmptyState',
          file: 'EmptyState.tsx',
        },
        {
          exported: 'ErrorBoundary',
          file: 'ErrorBoundary.tsx',
        },
        {
          exported: 'Sheet',
          file: 'Modal.tsx',
        },
        {
          exported: 'Skeleton',
          file: 'Skeleton.tsx',
        },
        {
          exported: 'TextField / SelectField / TextAreaField',
          file: 'Field.tsx',
        },
        {
          exported: 'ThemeToggle',
          file: 'ThemeToggle.tsx',
        },
        {
          exported: 'Toast',
          file: 'Toast.tsx',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdatePrompt.tsx',
        },
        {
          exported: 'useTheme',
          file: 'theme.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-family-map': {
      symbols: [
        'AppVersion',
        'Badge',
        'Button',
        'EmptyState',
        'ErrorBanner',
        'FamilyApps',
        'ObservabilityBoundary',
        'SelectField',
        'ShareButton',
        'Sheet',
        'SkeletonGroup',
        'TextAreaField',
        'TextField',
        'UpdateButton',
        'UpdatePromptBanner',
        'VersionProvider',
        'baseTestOptions',
        'clusterByGrid',
        'clustersToMarkers',
        'coveragePreset',
        'createChannel',
        'createLogger',
        'createMapLibreMapProvider',
        'createStore',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'dumpAppState',
        'expectNoA11yViolations',
        'installCorrelation',
        'installObservability',
        'isClusterId',
        'localRealtimeTransport',
        'mapCspDirectives',
        'mapTileRuntimeCaching',
        'osmRasterTiles',
        'prefetch',
        'pwaSeoPlugin',
        'rethrowWithState',
        'useOnline',
        'versionPlugin',
      ],
      subpaths: [
        '/correlation',
        '/logger',
        '/map',
        '/map/maplibre',
        '/playwright-a11y',
        '/playwright-base',
        '/prefetch',
        '/react',
        '/react/app-version',
        '/react/observability',
        '/react/share-button',
        '/react/update-prompt-banner',
        '/react/version',
        '/realtime',
        '/realtime/local',
        '/storage',
        '/vite-csp',
        '/vite-pwa-base',
        '/vite-version',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'geo',
          file: 'geo.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-footcoach': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/i18n',
        '/react/observability',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'Badge',
          file: 'Badge.tsx',
        },
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'Button',
          file: 'Button.tsx',
        },
        {
          exported: 'EmptyState',
          file: 'EmptyState.tsx',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'Toast',
          file: 'Toast.tsx',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdateBanner.tsx',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-molkky': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'coveragePreset',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
      ],
      subpaths: [
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/observability',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'AppFooter',
          file: 'AppFooter.tsx',
        },
        {
          exported: 'applyUpdate',
          file: 'register-sw.ts',
        },
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'ConfirmDialog',
          file: 'ConfirmDialog.tsx',
        },
        {
          exported: 'share',
          file: 'share.ts',
        },
        {
          exported: 'Sheet',
          file: 'Modal.tsx',
        },
        {
          exported: 'Skeleton',
          file: 'Skeleton.tsx',
        },
        {
          exported: 'useI18n',
          file: 'useI18n.ts',
        },
        {
          exported: 'useOnline',
          file: 'useOnline.ts',
        },
        {
          exported: 'useTheme',
          file: 'theme.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-puzzle': {
      symbols: [
        'ErrorBoundary',
        'FamilyApps',
        'baseTestOptions',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'resolveSeoPublicUrls',
      ],
      subpaths: [
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/observability',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'BottomNav',
          file: 'Navbar.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'security',
          file: 'security.ts',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdateBanner.tsx',
        },
        {
          exported: 'webVitals',
          file: 'web-vitals.ts',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-qowa': {
      symbols: [
        'baseTestOptions',
        'coveragePreset',
        'definePwaPlaywrightConfig',
      ],
      subpaths: ['/playwright-base', '/vitest-base'],
      duplicates: [
        {
          exported: 'AppFooter',
          file: 'AppFooter.tsx',
        },
        {
          exported: 'ConfirmDialog',
          file: 'ConfirmDialog.tsx',
        },
        {
          exported: 'ErrorBoundary',
          file: 'ErrorBoundary.tsx',
        },
        {
          exported: 'links',
          file: 'links.ts',
        },
        {
          exported: 'share',
          file: 'share.ts',
        },
        {
          exported: 'UpdatePromptBanner',
          file: 'UpdatePrompt.tsx',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
    'mister-quota': {
      symbols: [],
      subpaths: [],
      duplicates: [
        {
          exported: 'ConfirmDialog',
          file: 'ConfirmDialog.tsx',
        },
        {
          exported: 'ErrorBoundary',
          file: 'ErrorBoundary.tsx',
        },
        {
          exported: 'format',
          file: 'format.ts',
        },
        {
          exported: 'Toast',
          file: 'Toaster.tsx',
        },
      ],
      measuredAt: '2026-08-29T14:11:54.054Z',
    },
  },
  bySymbol: {
    ErrorBoundary: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'mister-cim10',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    FamilyApps: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    baseTestOptions: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
      'mister-qowa',
    ],
    clearErrorLog: ['miss-badminton'],
    cspPlugin: [
      'miss-badminton',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    definePwaPlaywrightConfig: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-supaboss',
      'mister-cim10',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
      'mister-qowa',
    ],
    expectNoA11yViolations: [
      'miss-badminton',
      'miss-carbook',
      'miss-genius',
      'miss-uwh',
      'mister-cim10',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    getErrorLog: ['miss-badminton'],
    initSentry: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    installErrorReporter: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    pwaSeoPlugin: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    recordError: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    createI18n: [
      'miss-carbook',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
    ],
    I18nPaths: ['miss-supaboss'],
    coveragePreset: [
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-qowa',
    ],
    createTranslator: ['miss-supaboss', 'miss-uwh'],
    useTheme: ['miss-supaboss'],
    useUpdatePrompt: ['miss-supaboss'],
    useReducedMotion: ['mister-doc'],
    AppVersion: ['mister-family-map'],
    Badge: ['mister-family-map'],
    Button: ['mister-family-map'],
    EmptyState: ['mister-family-map'],
    ErrorBanner: ['mister-family-map'],
    ObservabilityBoundary: ['mister-family-map'],
    SelectField: ['mister-family-map'],
    ShareButton: ['mister-family-map'],
    Sheet: ['mister-family-map'],
    SkeletonGroup: ['mister-family-map'],
    TextAreaField: ['mister-family-map'],
    TextField: ['mister-family-map'],
    UpdateButton: ['mister-family-map'],
    UpdatePromptBanner: ['mister-family-map'],
    VersionProvider: ['mister-family-map'],
    clusterByGrid: ['mister-family-map'],
    clustersToMarkers: ['mister-family-map'],
    createChannel: ['mister-family-map'],
    createLogger: ['mister-family-map'],
    createMapLibreMapProvider: ['mister-family-map'],
    createStore: ['mister-family-map'],
    dumpAppState: ['mister-family-map'],
    installCorrelation: ['mister-family-map'],
    installObservability: ['mister-family-map'],
    isClusterId: ['mister-family-map'],
    localRealtimeTransport: ['mister-family-map'],
    mapCspDirectives: ['mister-family-map'],
    mapTileRuntimeCaching: ['mister-family-map'],
    osmRasterTiles: ['mister-family-map'],
    prefetch: ['mister-family-map'],
    rethrowWithState: ['mister-family-map'],
    useOnline: ['mister-family-map'],
    versionPlugin: ['mister-family-map'],
    resolveSeoPublicUrls: ['mister-puzzle'],
  },
  byDuplicate: {
    applyUpdate: [
      'miss-badminton',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-uwh',
      'mister-cim10',
      'mister-molkky',
    ],
    backup: [
      'miss-badminton',
      'miss-contraction',
      'miss-genius',
      'miss-uwh',
      'mister-cim10',
      'mister-family-map',
      'mister-molkky',
    ],
    ConfirmDialog: [
      'miss-badminton',
      'miss-genius',
      'miss-uwh',
      'mister-doc',
      'mister-molkky',
      'mister-qowa',
      'mister-quota',
    ],
    links: [
      'miss-badminton',
      'miss-dice',
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-footcoach',
      'mister-qowa',
    ],
    share: ['miss-badminton', 'miss-dice', 'mister-molkky', 'mister-qowa'],
    Sheet: [
      'miss-badminton',
      'miss-dice',
      'miss-genius',
      'miss-uwh',
      'mister-doc',
      'mister-molkky',
    ],
    useI18n: [
      'miss-badminton',
      'miss-contraction',
      'miss-dice',
      'mister-molkky',
    ],
    useOnline: [
      'miss-badminton',
      'miss-supaboss',
      'miss-ticket-pwa',
      'mister-molkky',
    ],
    useTheme: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-ticket-pwa',
      'mister-cim10',
      'mister-doc',
      'mister-molkky',
    ],
    EmptyState: [
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-footcoach',
    ],
    format: [
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'miss-uwh',
      'mister-puzzle',
      'mister-quota',
    ],
    security: ['miss-carbook', 'miss-contraction', 'mister-puzzle'],
    ThemeToggle: [
      'miss-carbook',
      'miss-lookhouse',
      'miss-ticket-pwa',
      'mister-cim10',
      'mister-doc',
    ],
    Toast: [
      'miss-carbook',
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-footcoach',
      'mister-quota',
    ],
    UpdatePromptBanner: [
      'miss-carbook',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-footcoach',
      'mister-puzzle',
      'mister-qowa',
    ],
    webVitals: [
      'miss-carbook',
      'miss-contraction',
      'mister-cim10',
      'mister-puzzle',
    ],
    AppFooter: [
      'miss-contraction',
      'miss-genius',
      'miss-uwh',
      'mister-cim10',
      'mister-molkky',
      'mister-qowa',
    ],
    BottomNav: [
      'miss-contraction',
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-puzzle',
    ],
    ErrorBoundary: [
      'miss-dice',
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-qowa',
      'mister-quota',
    ],
    Button: ['miss-genius', 'miss-uwh', 'mister-doc', 'mister-footcoach'],
    'TextField / SelectField / TextAreaField': [
      'miss-genius',
      'miss-uwh',
      'mister-doc',
    ],
    geo: ['miss-lookhouse', 'mister-family-map'],
    Skeleton: ['miss-supaboss', 'mister-doc', 'mister-molkky'],
    Badge: ['mister-doc', 'mister-footcoach'],
  },
};
