/*
 * FICHIER GÉNÉRÉ — ne pas modifier à la main.
 *
 * Ce que chaque app importe RÉELLEMENT du paquet, et ce qu'elle recopie encore
 * à côté. Écrit par `scripts/measure-adoption.mjs`, qui exige les dépôts des
 * apps clonés à côté de celui-ci — ce que la CI n'a pas.
 *
 * Chargé par un `<script src>` classique, comme `metrics.js` : la page ne fait
 * AUCUNE requête réseau et s'ouvre en `file://`.
 *
 * `measured: 0` = le relevé n'a jamais tourné. La vitrine n'affiche alors
 * simplement aucun taux d'adoption.
 *
 * RELEVÉ CUMULÉ. `measured` compte les apps que cet enregistrement CONNAÎT,
 * pas celles vues à la dernière exécution : chaque entrée porte son propre
 * `measuredAt`. Personne n'ayant les dix-sept dépôts clonés en permanence,
 * l'écriture fusionne au lieu de remplacer — sans quoi un relevé partiel
 * effacerait le travail des autres.
 */
globalThis.SHOWROOM_ADOPTION = {
  generatedAt: '2026-08-31T17:54:30.081Z',
  measured: 17,
  total: 17,
  apps: {
    'miss-badminton': {
      symbols: [
        'AppUpdates',
        'ConfirmDialog',
        'ErrorBoundary',
        'FamilyApps',
        'LABELS',
        'LabelOverrides',
        'LabelsProvider',
        'RegisterSW',
        'SPONSOR_URL',
        'Sheet',
        'Sparkline',
        'ThemePreference',
        'ThemeProvider',
        'baseTestOptions',
        'clearErrorLog',
        'createI18n',
        'createIdb',
        'cspPlugin',
        'currentAppUrl',
        'dateSlug',
        'definePwaPlaywrightConfig',
        'downloadJson',
        'expectNoA11yViolations',
        'getErrorLog',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'readJsonFile',
        'recordError',
        'registerSW',
        'repoUrl',
        'shareOrCopy',
        'swStub',
        'unregisterServiceWorkers',
        'useAppUpdates',
        'useOnline',
        'useThemeContext',
        'useUpdatePrompt',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/download',
        '/idb',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/app-updates',
        '/react/confirm-dialog',
        '/react/i18n',
        '/react/labels',
        '/react/observability',
        '/react/sheet',
        '/react/sparkline',
        '/react/use-online',
        '/react/use-update-prompt',
        '/share',
        '/sw-update',
        '/tailwind-preset.css',
        '/testing/pwa-register',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-carbook': {
      symbols: [
        'ChannelStatus',
        'ConfirmDialog',
        'EmptyState',
        'ErrorBoundary',
        'FamilyApps',
        'STATUS',
        'Sheet',
        'SupabaseChange',
        'ThemePreference',
        'ThemeProvider',
        'ToastProvider',
        'UpdatePromptBanner',
        'baseTestOptions',
        'compressImageToMaxBytes',
        'createChannel',
        'createI18n',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'initWebVitals',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'stripImageMetadata',
        'supabaseRealtimeTransport',
        'useOnline',
        'useThemeContext',
        'useToast',
        'useUpdatePrompt',
        'validateImageFile',
      ],
      subpaths: [
        '/components.css',
        '/image',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/confirm-dialog',
        '/react/empty-state',
        '/react/i18n',
        '/react/observability',
        '/react/sheet',
        '/react/toast',
        '/react/update-prompt-banner',
        '/react/use-online',
        '/react/use-update-prompt',
        '/realtime',
        '/realtime/supabase',
        '/tailwind-preset.css',
        '/vite-pwa-base',
        '/vitest-base',
        '/web-vitals',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-contraction': {
      symbols: [
        'EmptyState',
        'ErrorBoundary',
        'FamilyApps',
        'LabelsProvider',
        'PAGE',
        'PdfContent',
        'ResolvedTheme',
        'ThemePreference',
        'applyUpdate',
        'baseTestOptions',
        'buildPdf',
        'dateSlug',
        'definePwaPlaywrightConfig',
        'downloadPdf',
        'initSentry',
        'initWebVitals',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'textWidth',
        'themeBootSource',
        'unregisterServiceWorkers',
        'useLabels',
        'useTheme',
        'useWakeLock',
        'vibrate',
      ],
      subpaths: [
        '/download',
        '/haptics',
        '/pdf',
        '/playwright-base',
        '/react',
        '/react/empty-state',
        '/react/labels',
        '/react/observability',
        '/react/use-theme',
        '/react/use-wake-lock',
        '/sw-update',
        '/tailwind-preset.css',
        '/theme-boot',
        '/vite-pwa-base',
        '/vitest-base',
        '/web-vitals',
      ],
      duplicates: [
        {
          exported: 'AppFooter',
          file: 'AppFooter.tsx',
        },
        {
          exported: 'backup',
          file: 'storage.ts',
        },
        {
          exported: 'BottomNav',
          file: 'BottomNav.tsx',
        },
        {
          exported: 'useI18n',
          file: 'useI18n.ts',
        },
      ],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-dice': {
      symbols: [
        'AppUpdates',
        'FamilyApps',
        'I18nApi',
        'I18nPaths',
        'LABELS',
        'LabelOverrides',
        'LabelsProvider',
        'RegisterSW',
        'SPONSOR_URL',
        'Sheet',
        'ThemePreference',
        'ThemeProvider',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'createTranslator',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'downloadText',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'pagesUrl',
        'pwaSeoPlugin',
        'recordError',
        'registerSW',
        'repoUrl',
        'shareOrCopy',
        'swStub',
        'unregisterServiceWorkers',
        'useThemeContext',
        'useWakeLock',
      ],
      subpaths: [
        '/apps-catalog',
        '/download',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/app-updates',
        '/react/i18n',
        '/react/labels',
        '/react/observability',
        '/react/sheet',
        '/react/theme-provider',
        '/react/use-theme',
        '/react/use-update-prompt',
        '/react/use-wake-lock',
        '/share',
        '/sw-update',
        '/testing/pwa-register',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-genius': {
      symbols: [
        'AppFooter',
        'BottomNav',
        'Button',
        'ConfirmDialog',
        'EmptyState',
        'ErrorBoundary',
        'FamilyApps',
        'SelectField',
        'Sheet',
        'TextField',
        'UpdatePromptBanner',
        'applyUpdate',
        'baseTestOptions',
        'createI18n',
        'createVersionedStore',
        'cspPlugin',
        'dateSlug',
        'definePwaPlaywrightConfig',
        'downloadText',
        'expectNoA11yViolations',
        'formatNumber',
        'getDefaultLocale',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'repoUrl',
        'setDefaultLocale',
        'useUpdatePrompt',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/download',
        '/format',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/app-footer',
        '/react/bottom-nav',
        '/react/button',
        '/react/confirm-dialog',
        '/react/empty-state',
        '/react/field',
        '/react/i18n',
        '/react/observability',
        '/react/sheet',
        '/react/update-prompt-banner',
        '/react/use-update-prompt',
        '/sw-update',
        '/tailwind-preset.css',
        '/versioned-store',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-lookhouse': {
      symbols: [
        'AppFooter',
        'Badge',
        'BadgeTone',
        'BottomNav',
        'IconsProvider',
        'SPONSOR_URL',
        'Sparkline',
        'SyncQueue',
        'SyncQueueEntry',
        'SyncQueueOptions',
        'ThemeProvider',
        'ThemeToggle',
        'baseTestOptions',
        'createStore',
        'createSupabaseClientFactory',
        'createSyncQueue',
        'formatCurrency',
        'formatDate',
        'formatNumber',
        'formatRelativeTime',
        'getDefaultLocale',
        'isValidCoordinates',
        'repoUrl',
        'setDefaultLocale',
        'supabaseConfig',
        'useThemeContext',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/format',
        '/geo',
        '/react/app-footer',
        '/react/badge',
        '/react/bottom-nav',
        '/react/icons-context',
        '/react/sparkline',
        '/react/theme-provider',
        '/react/theme-toggle',
        '/storage',
        '/supabase-client',
        '/sync-queue',
        '/tailwind-preset.css',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-supaboss': {
      symbols: [
        'Badge',
        'BadgeTone',
        'BottomNav',
        'ConfirmDialog',
        'EmptyState',
        'FamilyApps',
        'I18nPaths',
        'IconComponent',
        'IconsProvider',
        'ObservabilityBoundary',
        'Skeleton',
        'SkeletonGroup',
        'ToastViewport',
        'UpdatePromptBanner',
        'appById',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'createTranslator',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'formatDateTime',
        'formatPercentage',
        'formatRelativeTime',
        'formatUsage',
        'getDefaultLocale',
        'initSentry',
        'installErrorReporter',
        'repoUrl',
        'setDefaultLocale',
        'useOnline',
        'useTheme',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/format',
        '/playwright-base',
        '/react',
        '/react/badge',
        '/react/bottom-nav',
        '/react/confirm-dialog',
        '/react/empty-state',
        '/react/error-boundary',
        '/react/i18n',
        '/react/icons-context',
        '/react/observability',
        '/react/skeleton',
        '/react/toast',
        '/react/update-prompt-banner',
        '/react/use-online',
        '/tailwind-preset.css',
        '/vite-csp',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-ticket-pwa': {
      symbols: [
        'ALPHABETS',
        'ErrorBoundary',
        'FamilyApps',
        'IconsProvider',
        'LabelsProvider',
        'SPONSOR_URL',
        'ThemeProvider',
        'ThemeToggle',
        'baseTestOptions',
        'createI18n',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'generateCode',
        'initSentry',
        'installErrorReporter',
        'lucideIconSet',
        'parseDeepLink',
        'pwaSeoPlugin',
        'recordError',
        'repoUrl',
        'swStub',
        'unregisterServiceWorkers',
        'useOnline',
        'useThemeContext',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/pairing',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/i18n',
        '/react/icons-lucide',
        '/react/observability',
        '/react/use-online',
        '/sw-update',
        '/testing/pwa-register',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'miss-uwh': {
      symbols: [
        'AppFooter',
        'Button',
        'ConfirmDialog',
        'EmptyState',
        'FamilyApps',
        'ICAL_MIME',
        'IcalEvent',
        'LabelsProvider',
        'SelectField',
        'Sheet',
        'SyncQueue',
        'SyncQueueEntry',
        'TextAreaField',
        'TextField',
        'ToastViewport',
        'UpdatePromptBanner',
        'XlsxSheet',
        'applyUpdate',
        'baseTestOptions',
        'buildXlsx',
        'coveragePreset',
        'createI18n',
        'createStore',
        'createSupabaseClientFactory',
        'createSyncQueue',
        'createTranslator',
        'createVersionedStore',
        'cspPlugin',
        'downloadText',
        'downloadXlsx',
        'expectNoA11yViolations',
        'formatDate',
        'formatDateTime',
        'formatNumber',
        'initSentry',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'repoUrl',
        'setDefaultLocale',
        'toIcalendar',
        'unescapeText',
        'unfoldLines',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/download',
        '/format',
        '/ical',
        '/playwright-a11y',
        '/react',
        '/react/app-footer',
        '/react/button',
        '/react/confirm-dialog',
        '/react/empty-state',
        '/react/field',
        '/react/i18n',
        '/react/labels',
        '/react/observability',
        '/react/sheet',
        '/react/toast',
        '/react/update-prompt-banner',
        '/storage',
        '/supabase-client',
        '/sw-update',
        '/sync-queue',
        '/tailwind-preset.css',
        '/versioned-store',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
        '/xlsx',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-cim10': {
      symbols: [
        'AppFooter',
        'AppUpdates',
        'BottomNav',
        'ConfirmDialog',
        'ErrorBoundary',
        'FamilyApps',
        'LabelsProvider',
        'SPONSOR_URL',
        'ThemeProvider',
        'ThemeToggle',
        'UpdateButton',
        'baseTestOptions',
        'createI18n',
        'dateSlug',
        'definePwaPlaywrightConfig',
        'downloadBlob',
        'expectNoA11yViolations',
        'initSentry',
        'initWebVitals',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'repoUrl',
        'swStub',
        'toCsv',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/csv',
        '/download',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/app-footer',
        '/react/app-updates',
        '/react/bottom-nav',
        '/react/confirm-dialog',
        '/react/i18n',
        '/react/labels',
        '/react/observability',
        '/react/theme-toggle',
        '/react/update-button',
        '/tailwind-preset.css',
        '/testing/pwa-register',
        '/vite-pwa-base',
        '/vitest-base',
        '/web-vitals',
      ],
      duplicates: [
        {
          exported: 'backup',
          file: 'storage.ts',
        },
      ],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-doc': {
      symbols: [
        'BottomNav',
        'Button',
        'ConfirmDialog',
        'EmptyState',
        'FamilyApps',
        'IconsProvider',
        'LabelsProvider',
        'PAGE',
        'PdfContent',
        'PushSupport',
        'PushTransport',
        'RegisterSW',
        'Rgb',
        'Sheet',
        'Skeleton',
        'SkeletonGroup',
        'TextField',
        'ThemeProvider',
        'ToastProvider',
        'UpdatePromptBanner',
        'XlsxValue',
        'baseTestOptions',
        'buildPdf',
        'buildXlsx',
        'coveragePreset',
        'createI18n',
        'createPushClient',
        'downloadPdf',
        'downloadXlsx',
        'initSentry',
        'installErrorReporter',
        'lucideIconSet',
        'permissionState',
        'pushSupport',
        'pwaSeoPlugin',
        'recordError',
        'textWidth',
        'useReducedMotion',
        'useThemeContext',
        'useToast',
      ],
      subpaths: [
        '/components.css',
        '/pdf',
        '/push',
        '/react',
        '/react/bottom-nav',
        '/react/button',
        '/react/confirm-dialog',
        '/react/empty-state',
        '/react/field',
        '/react/i18n',
        '/react/icons-context',
        '/react/icons-lucide',
        '/react/labels',
        '/react/observability',
        '/react/sheet',
        '/react/skeleton',
        '/react/theme-provider',
        '/react/toast',
        '/react/update-prompt-banner',
        '/react/use-update-prompt',
        '/tailwind-preset.css',
        '/vite-pwa-base',
        '/vitest-base',
        '/xlsx',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-family-map': {
      symbols: [
        'AppVersion',
        'Badge',
        'BoundingBox',
        'Button',
        'Coordinates',
        'EmptyState',
        'ErrorBanner',
        'FamilyApps',
        'ObservabilityBoundary',
        'SelectField',
        'ShareButton',
        'Sheet',
        'SkeletonGroup',
        'TextAreaField',
        'TextField',
        'UpdateButton',
        'UpdatePromptBanner',
        'VersionProvider',
        'baseTestOptions',
        'clusterByGrid',
        'clustersToMarkers',
        'coveragePreset',
        'createChannel',
        'createLogger',
        'createMapLibreMapProvider',
        'createStore',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'distanceKm',
        'dumpAppState',
        'expectNoA11yViolations',
        'formatDistance',
        'installCorrelation',
        'installObservability',
        'isClusterId',
        'isInBoundingBox',
        'isValidCoordinates',
        'isValidLatitude',
        'isValidLongitude',
        'localRealtimeTransport',
        'mapCspDirectives',
        'mapTileRuntimeCaching',
        'osmRasterTiles',
        'prefetch',
        'pwaSeoPlugin',
        'rethrowWithState',
        'useOnline',
        'versionPlugin',
      ],
      subpaths: [
        '/components.css',
        '/correlation',
        '/geo',
        '/logger',
        '/map',
        '/map/maplibre',
        '/playwright-a11y',
        '/playwright-base',
        '/prefetch',
        '/react',
        '/react/app-version',
        '/react/observability',
        '/react/share-button',
        '/react/update-prompt-banner',
        '/react/version',
        '/realtime',
        '/realtime/local',
        '/storage',
        '/tailwind-preset.css',
        '/vite-csp',
        '/vite-pwa-base',
        '/vite-version',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-footcoach': {
      symbols: [
        'Badge',
        'BottomNav',
        'BottomNavItem',
        'Button',
        'ConfirmDialog',
        'EmptyState',
        'ErrorBoundary',
        'FamilyApps',
        'ICAL_MIME',
        'IcalEvent',
        'IconsProvider',
        'RegisterSW',
        'SPONSOR_URL',
        'Sheet',
        'ToastProvider',
        'UpdatePromptBanner',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'downloadText',
        'expectNoA11yViolations',
        'initSentry',
        'installErrorReporter',
        'lucideIconSet',
        'pwaSeoPlugin',
        'recordError',
        'repoUrl',
        'toIcalendar',
        'useToast',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/download',
        '/ical',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/badge',
        '/react/bottom-nav',
        '/react/button',
        '/react/confirm-dialog',
        '/react/empty-state',
        '/react/i18n',
        '/react/icons-context',
        '/react/icons-lucide',
        '/react/observability',
        '/react/sheet',
        '/react/toast',
        '/react/update-prompt-banner',
        '/react/use-update-prompt',
        '/tailwind-preset.css',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-molkky': {
      symbols: [
        'ALPHABETS',
        'AppFooter',
        'AppUpdates',
        'ConfirmDialog',
        'ErrorBoundary',
        'FamilyApps',
        'IconsProvider',
        'LabelsProvider',
        'PairingAlphabet',
        'Sheet',
        'Skeleton',
        'SkeletonGroup',
        'Sparkline',
        'ThemePreference',
        'ThemeProvider',
        'applyUpdate',
        'baseTestOptions',
        'coveragePreset',
        'createI18n',
        'cspPlugin',
        'dateSlug',
        'definePwaPlaywrightConfig',
        'downloadJson',
        'expectNoA11yViolations',
        'generateCode',
        'initSentry',
        'installErrorReporter',
        'lucideIconSet',
        'normalizeCode',
        'pwaSeoPlugin',
        'qrToDataUrl',
        'recordError',
        'repoUrl',
        'shareOrCopy',
        'swStub',
        'unregisterServiceWorkers',
        'useOnline',
        'useQrScanner',
        'useThemeContext',
        'useWakeLock',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/download',
        '/pairing',
        '/playwright-a11y',
        '/playwright-base',
        '/qr',
        '/react',
        '/react/app-updates',
        '/react/confirm-dialog',
        '/react/i18n',
        '/react/icons-context',
        '/react/icons-lucide',
        '/react/labels',
        '/react/observability',
        '/react/sheet',
        '/react/skeleton',
        '/react/sparkline',
        '/react/use-online',
        '/react/use-qr-scanner',
        '/react/use-wake-lock',
        '/share',
        '/sw-update',
        '/tailwind-preset.css',
        '/testing/pwa-register',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
      ],
      duplicates: [
        {
          exported: 'backup',
          file: 'storage.ts',
        },
      ],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-puzzle': {
      symbols: [
        'ConfirmDialog',
        'ErrorBoundary',
        'FamilyApps',
        'IMAGE_ACCEPTED_TYPES',
        'UpdatePromptBanner',
        'baseTestOptions',
        'compressImageToMaxBytes',
        'cspPlugin',
        'definePwaPlaywrightConfig',
        'expectNoA11yViolations',
        'initSentry',
        'initWebVitals',
        'installErrorReporter',
        'pwaSeoPlugin',
        'recordError',
        'resolveSeoPublicUrls',
        'stripImageMetadata',
        'validateImageFile',
      ],
      subpaths: [
        '/components.css',
        '/image',
        '/playwright-a11y',
        '/playwright-base',
        '/react',
        '/react/confirm-dialog',
        '/react/observability',
        '/react/update-prompt-banner',
        '/tailwind-preset.css',
        '/vite-csp',
        '/vite-pwa-base',
        '/vitest-base',
        '/web-vitals',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-qowa': {
      symbols: [
        'AppFooter',
        'AppUpdates',
        'ConfirmDialog',
        'ErrorBoundary',
        'SPONSOR_URL',
        'ShareResult',
        'baseTestOptions',
        'coveragePreset',
        'currentAppUrl',
        'definePwaPlaywrightConfig',
        'downloadJson',
        'downloadText',
        'generateCode',
        'normalizeCode',
        'parseCsv',
        'qrToSvg',
        'readJsonFile',
        'repoUrl',
        'shareOrCopy',
        'toCsv',
        'useInstallPrompt',
      ],
      subpaths: [
        '/apps-catalog',
        '/components.css',
        '/csv',
        '/download',
        '/pairing',
        '/playwright-base',
        '/qr',
        '/react/app-footer',
        '/react/app-updates',
        '/react/confirm-dialog',
        '/react/error-boundary',
        '/react/use-install-prompt',
        '/share',
        '/tailwind-preset.css',
        '/vitest-base',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
    'mister-quota': {
      symbols: [
        'ConfirmDialog',
        'ObservabilityBoundary',
        'ToastViewport',
        'formatCurrency',
        'formatDateTime',
        'formatNumber',
      ],
      subpaths: [
        '/components.css',
        '/format',
        '/react/confirm-dialog',
        '/react/error-boundary',
        '/react/toast',
      ],
      duplicates: [],
      measuredAt: '2026-08-31T17:54:30.081Z',
    },
  },
  bySymbol: {
    AppUpdates: [
      'miss-badminton',
      'miss-dice',
      'mister-cim10',
      'mister-molkky',
      'mister-qowa',
    ],
    ConfirmDialog: [
      'miss-badminton',
      'miss-carbook',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
      'mister-qowa',
      'mister-quota',
    ],
    ErrorBoundary: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-ticket-pwa',
      'mister-cim10',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
      'mister-qowa',
    ],
    FamilyApps: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    LABELS: ['miss-badminton', 'miss-dice'],
    LabelOverrides: ['miss-badminton', 'miss-dice'],
    LabelsProvider: [
      'miss-badminton',
      'miss-contraction',
      'miss-dice',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-molkky',
    ],
    RegisterSW: [
      'miss-badminton',
      'miss-dice',
      'mister-doc',
      'mister-footcoach',
    ],
    SPONSOR_URL: [
      'miss-badminton',
      'miss-dice',
      'miss-lookhouse',
      'miss-ticket-pwa',
      'mister-cim10',
      'mister-footcoach',
      'mister-qowa',
    ],
    Sheet: [
      'miss-badminton',
      'miss-carbook',
      'miss-dice',
      'miss-genius',
      'miss-uwh',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
    ],
    Sparkline: ['miss-badminton', 'miss-lookhouse', 'mister-molkky'],
    ThemePreference: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'mister-molkky',
    ],
    ThemeProvider: [
      'miss-badminton',
      'miss-carbook',
      'miss-dice',
      'miss-lookhouse',
      'miss-ticket-pwa',
      'mister-cim10',
      'mister-doc',
      'mister-molkky',
    ],
    baseTestOptions: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
      'mister-qowa',
    ],
    clearErrorLog: ['miss-badminton'],
    createI18n: [
      'miss-badminton',
      'miss-carbook',
      'miss-dice',
      'miss-genius',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
    ],
    createIdb: ['miss-badminton'],
    cspPlugin: [
      'miss-badminton',
      'miss-dice',
      'miss-genius',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    currentAppUrl: ['miss-badminton', 'mister-qowa'],
    dateSlug: [
      'miss-badminton',
      'miss-contraction',
      'miss-genius',
      'mister-cim10',
      'mister-molkky',
    ],
    definePwaPlaywrightConfig: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-supaboss',
      'miss-ticket-pwa',
      'mister-cim10',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
      'mister-qowa',
    ],
    downloadJson: ['miss-badminton', 'mister-molkky', 'mister-qowa'],
    expectNoA11yViolations: [
      'miss-badminton',
      'miss-carbook',
      'miss-dice',
      'miss-genius',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    getErrorLog: ['miss-badminton'],
    initSentry: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    installErrorReporter: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    pwaSeoPlugin: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    readJsonFile: ['miss-badminton', 'mister-qowa'],
    recordError: [
      'miss-badminton',
      'miss-carbook',
      'miss-contraction',
      'miss-dice',
      'miss-genius',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
      'mister-puzzle',
    ],
    registerSW: ['miss-badminton', 'miss-dice'],
    repoUrl: [
      'miss-badminton',
      'miss-dice',
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'miss-ticket-pwa',
      'miss-uwh',
      'mister-cim10',
      'mister-footcoach',
      'mister-molkky',
      'mister-qowa',
    ],
    shareOrCopy: [
      'miss-badminton',
      'miss-dice',
      'mister-molkky',
      'mister-qowa',
    ],
    swStub: [
      'miss-badminton',
      'miss-dice',
      'miss-ticket-pwa',
      'mister-cim10',
      'mister-molkky',
    ],
    unregisterServiceWorkers: [
      'miss-badminton',
      'miss-contraction',
      'miss-dice',
      'miss-ticket-pwa',
      'mister-molkky',
    ],
    useAppUpdates: ['miss-badminton'],
    useOnline: [
      'miss-badminton',
      'miss-carbook',
      'miss-supaboss',
      'miss-ticket-pwa',
      'mister-family-map',
      'mister-molkky',
    ],
    useThemeContext: [
      'miss-badminton',
      'miss-carbook',
      'miss-dice',
      'miss-lookhouse',
      'miss-ticket-pwa',
      'mister-doc',
      'mister-molkky',
    ],
    useUpdatePrompt: ['miss-badminton', 'miss-carbook', 'miss-genius'],
    ChannelStatus: ['miss-carbook'],
    EmptyState: [
      'miss-carbook',
      'miss-contraction',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
    ],
    STATUS: ['miss-carbook'],
    SupabaseChange: ['miss-carbook'],
    ToastProvider: ['miss-carbook', 'mister-doc', 'mister-footcoach'],
    UpdatePromptBanner: [
      'miss-carbook',
      'miss-genius',
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-puzzle',
    ],
    compressImageToMaxBytes: ['miss-carbook', 'mister-puzzle'],
    createChannel: ['miss-carbook', 'mister-family-map'],
    initWebVitals: [
      'miss-carbook',
      'miss-contraction',
      'mister-cim10',
      'mister-puzzle',
    ],
    stripImageMetadata: ['miss-carbook', 'mister-puzzle'],
    supabaseRealtimeTransport: ['miss-carbook'],
    useToast: ['miss-carbook', 'mister-doc', 'mister-footcoach'],
    validateImageFile: ['miss-carbook', 'mister-puzzle'],
    PAGE: ['miss-contraction', 'mister-doc'],
    PdfContent: ['miss-contraction', 'mister-doc'],
    ResolvedTheme: ['miss-contraction'],
    applyUpdate: [
      'miss-contraction',
      'miss-genius',
      'miss-uwh',
      'mister-molkky',
    ],
    buildPdf: ['miss-contraction', 'mister-doc'],
    downloadPdf: ['miss-contraction', 'mister-doc'],
    textWidth: ['miss-contraction', 'mister-doc'],
    themeBootSource: ['miss-contraction'],
    useLabels: ['miss-contraction'],
    useTheme: ['miss-contraction', 'miss-supaboss'],
    useWakeLock: ['miss-contraction', 'miss-dice', 'mister-molkky'],
    vibrate: ['miss-contraction'],
    I18nApi: ['miss-dice'],
    I18nPaths: ['miss-dice', 'miss-supaboss'],
    coveragePreset: [
      'miss-dice',
      'miss-supaboss',
      'miss-uwh',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
      'mister-molkky',
      'mister-qowa',
    ],
    createTranslator: ['miss-dice', 'miss-supaboss', 'miss-uwh'],
    downloadText: [
      'miss-dice',
      'miss-genius',
      'miss-uwh',
      'mister-footcoach',
      'mister-qowa',
    ],
    pagesUrl: ['miss-dice'],
    AppFooter: [
      'miss-genius',
      'miss-lookhouse',
      'miss-uwh',
      'mister-cim10',
      'mister-molkky',
      'mister-qowa',
    ],
    BottomNav: [
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'mister-cim10',
      'mister-doc',
      'mister-footcoach',
    ],
    Button: [
      'miss-genius',
      'miss-uwh',
      'mister-doc',
      'mister-family-map',
      'mister-footcoach',
    ],
    SelectField: ['miss-genius', 'miss-uwh', 'mister-family-map'],
    TextField: ['miss-genius', 'miss-uwh', 'mister-doc', 'mister-family-map'],
    createVersionedStore: ['miss-genius', 'miss-uwh'],
    formatNumber: ['miss-genius', 'miss-lookhouse', 'miss-uwh', 'mister-quota'],
    getDefaultLocale: ['miss-genius', 'miss-lookhouse', 'miss-supaboss'],
    setDefaultLocale: [
      'miss-genius',
      'miss-lookhouse',
      'miss-supaboss',
      'miss-uwh',
    ],
    Badge: [
      'miss-lookhouse',
      'miss-supaboss',
      'mister-family-map',
      'mister-footcoach',
    ],
    BadgeTone: ['miss-lookhouse', 'miss-supaboss'],
    IconsProvider: [
      'miss-lookhouse',
      'miss-supaboss',
      'miss-ticket-pwa',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
    ],
    SyncQueue: ['miss-lookhouse', 'miss-uwh'],
    SyncQueueEntry: ['miss-lookhouse', 'miss-uwh'],
    SyncQueueOptions: ['miss-lookhouse'],
    ThemeToggle: ['miss-lookhouse', 'miss-ticket-pwa', 'mister-cim10'],
    createStore: ['miss-lookhouse', 'miss-uwh', 'mister-family-map'],
    createSupabaseClientFactory: ['miss-lookhouse', 'miss-uwh'],
    createSyncQueue: ['miss-lookhouse', 'miss-uwh'],
    formatCurrency: ['miss-lookhouse', 'mister-quota'],
    formatDate: ['miss-lookhouse', 'miss-uwh'],
    formatRelativeTime: ['miss-lookhouse', 'miss-supaboss'],
    isValidCoordinates: ['miss-lookhouse', 'mister-family-map'],
    supabaseConfig: ['miss-lookhouse'],
    IconComponent: ['miss-supaboss'],
    ObservabilityBoundary: [
      'miss-supaboss',
      'mister-family-map',
      'mister-quota',
    ],
    Skeleton: ['miss-supaboss', 'mister-doc', 'mister-molkky'],
    SkeletonGroup: [
      'miss-supaboss',
      'mister-doc',
      'mister-family-map',
      'mister-molkky',
    ],
    ToastViewport: ['miss-supaboss', 'miss-uwh', 'mister-quota'],
    appById: ['miss-supaboss'],
    formatDateTime: ['miss-supaboss', 'miss-uwh', 'mister-quota'],
    formatPercentage: ['miss-supaboss'],
    formatUsage: ['miss-supaboss'],
    ALPHABETS: ['miss-ticket-pwa', 'mister-molkky'],
    generateCode: ['miss-ticket-pwa', 'mister-molkky', 'mister-qowa'],
    lucideIconSet: [
      'miss-ticket-pwa',
      'mister-doc',
      'mister-footcoach',
      'mister-molkky',
    ],
    parseDeepLink: ['miss-ticket-pwa'],
    ICAL_MIME: ['miss-uwh', 'mister-footcoach'],
    IcalEvent: ['miss-uwh', 'mister-footcoach'],
    TextAreaField: ['miss-uwh', 'mister-family-map'],
    XlsxSheet: ['miss-uwh'],
    buildXlsx: ['miss-uwh', 'mister-doc'],
    downloadXlsx: ['miss-uwh', 'mister-doc'],
    toIcalendar: ['miss-uwh', 'mister-footcoach'],
    unescapeText: ['miss-uwh'],
    unfoldLines: ['miss-uwh'],
    UpdateButton: ['mister-cim10', 'mister-family-map'],
    downloadBlob: ['mister-cim10'],
    toCsv: ['mister-cim10', 'mister-qowa'],
    PushSupport: ['mister-doc'],
    PushTransport: ['mister-doc'],
    Rgb: ['mister-doc'],
    XlsxValue: ['mister-doc'],
    createPushClient: ['mister-doc'],
    permissionState: ['mister-doc'],
    pushSupport: ['mister-doc'],
    useReducedMotion: ['mister-doc'],
    AppVersion: ['mister-family-map'],
    BoundingBox: ['mister-family-map'],
    Coordinates: ['mister-family-map'],
    ErrorBanner: ['mister-family-map'],
    ShareButton: ['mister-family-map'],
    VersionProvider: ['mister-family-map'],
    clusterByGrid: ['mister-family-map'],
    clustersToMarkers: ['mister-family-map'],
    createLogger: ['mister-family-map'],
    createMapLibreMapProvider: ['mister-family-map'],
    distanceKm: ['mister-family-map'],
    dumpAppState: ['mister-family-map'],
    formatDistance: ['mister-family-map'],
    installCorrelation: ['mister-family-map'],
    installObservability: ['mister-family-map'],
    isClusterId: ['mister-family-map'],
    isInBoundingBox: ['mister-family-map'],
    isValidLatitude: ['mister-family-map'],
    isValidLongitude: ['mister-family-map'],
    localRealtimeTransport: ['mister-family-map'],
    mapCspDirectives: ['mister-family-map'],
    mapTileRuntimeCaching: ['mister-family-map'],
    osmRasterTiles: ['mister-family-map'],
    prefetch: ['mister-family-map'],
    rethrowWithState: ['mister-family-map'],
    versionPlugin: ['mister-family-map'],
    BottomNavItem: ['mister-footcoach'],
    PairingAlphabet: ['mister-molkky'],
    normalizeCode: ['mister-molkky', 'mister-qowa'],
    qrToDataUrl: ['mister-molkky'],
    useQrScanner: ['mister-molkky'],
    IMAGE_ACCEPTED_TYPES: ['mister-puzzle'],
    resolveSeoPublicUrls: ['mister-puzzle'],
    ShareResult: ['mister-qowa'],
    parseCsv: ['mister-qowa'],
    qrToSvg: ['mister-qowa'],
    useInstallPrompt: ['mister-qowa'],
  },
  byDuplicate: {
    AppFooter: ['miss-contraction'],
    backup: ['miss-contraction', 'mister-cim10', 'mister-molkky'],
    BottomNav: ['miss-contraction'],
    useI18n: ['miss-contraction'],
  },
};
