/*
 * FICHIER GÉNÉRÉ — ne pas modifier à la main.
 *
 * Source : `apps-catalog.js` à la racine du paquet.
 * Régénérer : `npm run sync`.
 *
 * Le showroom ne peut pas `import` le catalogue (page statique, `file://`) :
 * il en lit ce miroir, posé sur `globalThis` comme `themes.js` et
 * `screenshots.js`. `test/apps-catalog.test.mjs` vérifie qu'il ne dérive pas.
 */
globalThis.SHOWROOM_APPS = {
  owner: 'mister-guiiug',
  sponsorUrl: 'https://buymeacoffee.com/mister.guiiug',
  maturities: ['alpha', 'beta', 'stable'],
  categories: ['sante', 'sport', 'jeux', 'education', 'outils', 'dev'],
  backends: ['supabase', 'firebase', 'local', 'api'],
  platforms: ['web', 'desktop'],
  configSubpaths: [
    'commitlint',
    'components.css',
    'eslint-react',
    'lint-staged',
    'playwright-a11y',
    'playwright-base',
    'prettier',
    'react',
    'react/i18n',
    'react/observability',
    'react/use-update-prompt',
    'tailwind-preset.css',
    'tsconfig-app-react',
    'tsconfig-node',
    'vite-csp',
    'vite-pwa-base',
    'vitest-base',
    'vitest-setup',
  ],
  configUsage: {
    'eslint-react': 15,
    'lint-staged': 13,
    'playwright-a11y': 9,
    'playwright-base': 12,
    prettier: 14,
    react: 13,
    'react/i18n': 8,
    'react/observability': 13,
    'tailwind-preset.css': 13,
    'tsconfig-app-react': 14,
    'tsconfig-node': 14,
    'vite-pwa-base': 12,
    'vitest-base': 14,
    'vitest-setup': 13,
    'vite-csp': 9,
    'components.css': 1,
    commitlint: 2,
    'react/use-update-prompt': 1,
  },
  apps: [
    {
      id: 'miss-carbook',
      name: 'Miss Carbook',
      description: 'Comparatif collaboratif de véhicules, en temps réel.',
      maturity: 'stable',
      category: 'outils',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-carbook',
      appUrl: 'https://mister-guiiug.github.io/miss-carbook/',
      iconUrl: 'https://mister-guiiug.github.io/miss-carbook/favicon.svg',
    },
    {
      id: 'miss-contraction',
      name: 'Miss Contraction',
      description: 'Chronomètre de contractions et alertes maternité.',
      maturity: 'stable',
      category: 'sante',
      backend: 'local',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-base',
        'prettier',
        'react',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-contraction',
      appUrl: 'https://mister-guiiug.github.io/miss-contraction/',
      iconUrl: 'https://mister-guiiug.github.io/miss-contraction/icon.svg',
    },
    {
      id: 'miss-genius',
      name: 'Miss Genius',
      description:
        'Simulateur de moyennes scolaires (notes, scénarios, objectifs).',
      maturity: 'stable',
      category: 'education',
      backend: 'local',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-genius',
      appUrl: 'https://mister-guiiug.github.io/miss-genius/',
      iconUrl: 'https://mister-guiiug.github.io/miss-genius/icons/icon-192.png',
    },
    {
      id: 'miss-uwh',
      name: 'Miss UWH',
      description:
        'Bilan comptable de saison pour club de hockey subaquatique.',
      maturity: 'stable',
      category: 'sport',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'components.css',
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-uwh',
      appUrl: 'https://mister-guiiug.github.io/miss-uwh/',
      iconUrl: 'https://mister-guiiug.github.io/miss-uwh/icons/icon-192.png',
    },
    {
      id: 'mister-cim10',
      name: 'Mister CIM-10',
      description:
        'Aide à la cotation CIM-10 dans le navigateur (export TXT/CSV/PDF).',
      maturity: 'stable',
      category: 'sante',
      backend: 'local',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-cim10',
      appUrl: 'https://mister-guiiug.github.io/mister-cim10/',
      iconUrl: 'https://mister-guiiug.github.io/mister-cim10/favicon.svg',
    },
    {
      id: 'mister-footcoach',
      name: 'Mister Footcoach',
      description:
        "Gestion d'équipes de foot : compositions, statistiques, entraînements.",
      maturity: 'stable',
      category: 'sport',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-footcoach',
      appUrl: 'https://mister-guiiug.github.io/mister-footcoach/',
      iconUrl: 'https://mister-guiiug.github.io/mister-footcoach/logo.svg',
    },
    {
      id: 'mister-puzzle',
      name: 'Mister Puzzle',
      description: 'Suivi collaboratif de progression de puzzle en temps réel.',
      maturity: 'stable',
      category: 'jeux',
      backend: 'firebase',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-puzzle',
      appUrl: 'https://mister-guiiug.github.io/mister-puzzle/',
      iconUrl: 'https://mister-guiiug.github.io/mister-puzzle/favicon.svg',
    },
    {
      id: 'miss-ticket-pwa',
      name: 'Miss Ticket',
      description: "Télécommande PWA pour l'application desktop Miss Ticket.",
      maturity: 'stable',
      category: 'outils',
      backend: 'firebase',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-ticket-pwa',
      appUrl: 'https://mister-guiiug.github.io/miss-ticket-pwa/',
      iconUrl: 'https://mister-guiiug.github.io/miss-ticket-pwa/favicon.svg',
    },
    {
      id: 'mister-doc',
      name: 'Mister Doc',
      description:
        'Planning de gardes de médecins synchronisé : vue mensuelle, compteurs week-end et heures.',
      maturity: 'beta',
      category: 'sante',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-doc',
      appUrl: 'https://mister-guiiug.github.io/mister-doc/',
      iconUrl: 'https://mister-guiiug.github.io/mister-doc/favicon.svg',
    },
    {
      id: 'miss-lookhouse',
      name: 'Miss Lookhouse',
      description:
        'Veille immobilière : multi-sources, anti-doublons, historique des prix, scoring explicable.',
      maturity: 'beta',
      category: 'outils',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'eslint-react',
        'prettier',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-lookhouse',
      appUrl: 'https://mister-guiiug.github.io/miss-lookhouse/',
      iconUrl: 'https://mister-guiiug.github.io/miss-lookhouse/favicon.svg',
    },
    {
      id: 'miss-badminton',
      name: 'Miss Badminton',
      description: 'Suivi de scores et statistiques de badminton.',
      maturity: 'alpha',
      category: 'sport',
      backend: 'local',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-badminton',
      appUrl: 'https://mister-guiiug.github.io/miss-badminton/',
      iconUrl: 'https://mister-guiiug.github.io/miss-badminton/favicon.svg',
    },
    {
      id: 'miss-dice',
      name: 'Miss Dice',
      description: 'Lanceur de dé à 6 faces, 100 % hors ligne, installable.',
      maturity: 'alpha',
      category: 'jeux',
      backend: 'local',
      platform: 'web',
      configs: [
        'commitlint',
        'eslint-react',
        'lint-staged',
        'playwright-base',
        'prettier',
        'react',
        'react/observability',
        'vite-csp',
        'vite-pwa-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-dice',
      appUrl: 'https://mister-guiiug.github.io/miss-dice/',
      iconUrl: 'https://mister-guiiug.github.io/miss-dice/favicon.svg',
    },
    {
      id: 'miss-supaboss',
      name: 'Miss Supaboss',
      description:
        'Pilotage multi-comptes Supabase Free : pause/restore, quotas, démos.',
      maturity: 'alpha',
      category: 'dev',
      backend: 'api',
      platform: 'web',
      configs: [
        'commitlint',
        'eslint-react',
        'lint-staged',
        'playwright-base',
        'prettier',
        'react',
        'react/i18n',
        'react/observability',
        'react/use-update-prompt',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-supaboss',
      appUrl: 'https://mister-guiiug.github.io/miss-supaboss/',
      iconUrl: 'https://mister-guiiug.github.io/miss-supaboss/favicon.svg',
    },
    {
      id: 'mister-molkky',
      name: 'Mister Mölkky',
      description:
        'Compteur de scores pour parties de Mölkky (multi-appareils).',
      maturity: 'alpha',
      category: 'jeux',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/observability',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-molkky',
      appUrl: 'https://mister-guiiug.github.io/mister-molkky/',
      iconUrl: 'https://mister-guiiug.github.io/mister-molkky/logo.png',
    },
    {
      id: 'mister-qowa',
      name: 'Mister Qowa',
      description:
        "Quiz interactif en temps réel : l'animateur pilote, les joueurs répondent.",
      maturity: 'alpha',
      category: 'jeux',
      backend: 'firebase',
      platform: 'web',
      configs: [
        'eslint-react',
        'playwright-base',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vitest-base',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-qowa',
      appUrl: 'https://mister-guiiug.github.io/mister-qowa/',
      iconUrl: 'https://mister-guiiug.github.io/mister-qowa/icons/icon.svg',
    },
    {
      id: 'mister-quota',
      name: 'Mister Quota',
      description:
        'Suivi de consommation des services IA (application desktop).',
      maturity: 'alpha',
      category: 'dev',
      platform: 'desktop',
      configs: [],
      repoUrl: 'https://github.com/mister-guiiug/mister-quota',
      appUrl: 'https://github.com/mister-guiiug/mister-quota',
      iconUrl: null,
    },
  ],
};
