/*
 * FICHIER GÉNÉRÉ — ne pas modifier à la main.
 *
 * Source : `apps-catalog.js` à la racine du paquet.
 * Régénérer : `npm run sync`.
 *
 * Le showroom ne peut pas `import` le catalogue (page statique, `file://`) :
 * il en lit ce miroir, posé sur `globalThis` comme `themes.js` et
 * `screenshots.js`. `test/apps-catalog.test.mjs` vérifie qu'il ne dérive pas.
 */
globalThis.SHOWROOM_APPS = {
  owner: 'mister-guiiug',
  sponsorUrl: 'https://buymeacoffee.com/mister.guiiug',
  maturities: ['alpha', 'beta', 'stable'],
  categories: [
    'sante',
    'sport',
    'jeux',
    'loisirs',
    'education',
    'outils',
    'dev',
  ],
  backends: ['supabase', 'firebase', 'local', 'api'],
  platforms: ['web', 'desktop'],
  configSubpaths: [
    'apps-catalog',
    'backend',
    'commitlint',
    'components.css',
    'correlation',
    'csv',
    'download',
    'eslint-react',
    'format',
    'geo',
    'ical',
    'idb',
    'image',
    'lint-staged',
    'logger',
    'map',
    'map/maplibre',
    'pairing',
    'pdf',
    'playwright-a11y',
    'playwright-base',
    'prefetch',
    'prettier',
    'push',
    'qr',
    'react',
    'react/app-footer',
    'react/app-header',
    'react/app-updates',
    'react/app-version',
    'react/badge',
    'react/bottom-nav',
    'react/button',
    'react/card',
    'react/confirm-dialog',
    'react/empty-state',
    'react/error-boundary',
    'react/family-apps',
    'react/field',
    'react/i18n',
    'react/icons-context',
    'react/icons-lucide',
    'react/labels',
    'react/observability',
    'react/page-container',
    'react/rive',
    'react/segmented-control',
    'react/share-button',
    'react/sheet',
    'react/skeleton',
    'react/sparkline',
    'react/stat',
    'react/theme-provider',
    'react/theme-toggle',
    'react/toast',
    'react/update-prompt-banner',
    'react/use-install-prompt',
    'react/use-media-query',
    'react/use-online',
    'react/use-qr-scanner',
    'react/use-update-prompt',
    'react/use-wake-lock',
    'react/version',
    'realtime',
    'realtime/local',
    'realtime/supabase',
    'share',
    'storage',
    'supabase-client',
    'sw-update',
    'sync-queue',
    'tailwind-preset.css',
    'tsconfig-app-react',
    'tsconfig-node',
    'versioned-store',
    'vite-csp',
    'vite-pwa-base',
    'vite-version',
    'vitest-base',
    'vitest-setup',
    'web-vitals',
    'xlsx',
  ],
  configUsage: {
    'components.css': 17,
    'eslint-react': 18,
    image: 2,
    'lint-staged': 15,
    'playwright-a11y': 11,
    'playwright-base': 13,
    prettier: 18,
    react: 14,
    'react/confirm-dialog': 13,
    'react/empty-state': 8,
    'react/i18n': 8,
    'react/observability': 15,
    'react/sheet': 7,
    'react/toast': 7,
    'react/update-prompt-banner': 9,
    'react/use-online': 6,
    'react/use-update-prompt': 4,
    realtime: 2,
    'realtime/supabase': 1,
    'tailwind-preset.css': 16,
    'tsconfig-app-react': 17,
    'tsconfig-node': 17,
    'vite-pwa-base': 15,
    'vitest-base': 18,
    'vitest-setup': 17,
    'web-vitals': 3,
    download: 10,
    pdf: 2,
    'react/use-wake-lock': 3,
    'apps-catalog': 10,
    format: 7,
    'react/app-footer': 5,
    'react/bottom-nav': 8,
    'react/button': 6,
    'react/field': 4,
    'sw-update': 2,
    'versioned-store': 3,
    'vite-csp': 12,
    ical: 2,
    'react/labels': 5,
    storage: 4,
    'supabase-client': 3,
    'sync-queue': 2,
    xlsx: 2,
    csv: 2,
    'react/theme-toggle': 3,
    'react/badge': 5,
    'react/icons-context': 6,
    'react/icons-lucide': 5,
    pairing: 3,
    push: 1,
    'react/skeleton': 3,
    'react/theme-provider': 4,
    geo: 2,
    'react/sparkline': 3,
    idb: 1,
    commitlint: 4,
    share: 3,
    'react/error-boundary': 4,
    'react/app-header': 2,
    'react/card': 2,
    'react/family-apps': 1,
    'react/page-container': 2,
    'react/segmented-control': 1,
    'react/stat': 1,
    qr: 2,
    'react/use-qr-scanner': 1,
    'react/app-updates': 2,
    'react/use-install-prompt': 1,
    correlation: 1,
    logger: 1,
    map: 1,
    'map/maplibre': 1,
    prefetch: 1,
    'react/app-version': 1,
    'react/share-button': 1,
    'react/version': 1,
    'realtime/local': 1,
    'vite-version': 1,
    backend: 1,
    'react/rive': 1,
    'react/use-media-query': 1,
  },
  apps: [
    {
      id: 'miss-carbook',
      name: 'Miss Carbook',
      description: 'Comparatif collaboratif de véhicules, en temps réel.',
      maturity: 'alpha',
      category: 'outils',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'components.css',
        'eslint-react',
        'image',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/confirm-dialog',
        'react/empty-state',
        'react/i18n',
        'react/observability',
        'react/sheet',
        'react/toast',
        'react/update-prompt-banner',
        'react/use-online',
        'react/use-update-prompt',
        'realtime',
        'realtime/supabase',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
        'web-vitals',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-carbook',
      appUrl: 'https://mister-guiiug.github.io/miss-carbook/',
      iconUrl: 'https://mister-guiiug.github.io/miss-carbook/favicon.svg',
    },
    {
      id: 'miss-contraction',
      name: 'Miss Contraction',
      description: 'Chronomètre de contractions et alertes maternité.',
      maturity: 'stable',
      category: 'sante',
      backend: 'local',
      platform: 'web',
      configs: [
        'download',
        'eslint-react',
        'lint-staged',
        'pdf',
        'playwright-base',
        'prettier',
        'react',
        'react/observability',
        'react/use-wake-lock',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
        'web-vitals',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-contraction',
      appUrl: 'https://mister-guiiug.github.io/miss-contraction/',
      iconUrl: 'https://mister-guiiug.github.io/miss-contraction/icon.svg',
    },
    {
      id: 'miss-genius',
      name: 'Miss Genius',
      description:
        'Simulateur de moyennes scolaires (notes, scénarios, objectifs).',
      maturity: 'stable',
      category: 'education',
      backend: 'local',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'download',
        'eslint-react',
        'format',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/app-footer',
        'react/bottom-nav',
        'react/button',
        'react/confirm-dialog',
        'react/empty-state',
        'react/field',
        'react/i18n',
        'react/observability',
        'react/sheet',
        'react/update-prompt-banner',
        'react/use-update-prompt',
        'sw-update',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'versioned-store',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-genius',
      appUrl: 'https://mister-guiiug.github.io/miss-genius/',
      iconUrl: 'https://mister-guiiug.github.io/miss-genius/icons/icon-192.png',
    },
    {
      id: 'miss-uwh',
      name: 'Miss UWH',
      description:
        'Bilan comptable de saison pour club de hockey subaquatique.',
      maturity: 'stable',
      category: 'sport',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'download',
        'eslint-react',
        'format',
        'ical',
        'lint-staged',
        'playwright-a11y',
        'prettier',
        'react',
        'react/app-footer',
        'react/button',
        'react/confirm-dialog',
        'react/empty-state',
        'react/field',
        'react/i18n',
        'react/labels',
        'react/observability',
        'react/sheet',
        'react/toast',
        'react/update-prompt-banner',
        'storage',
        'supabase-client',
        'sw-update',
        'sync-queue',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'versioned-store',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
        'xlsx',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-uwh',
      appUrl: 'https://mister-guiiug.github.io/miss-uwh/',
      iconUrl: 'https://mister-guiiug.github.io/miss-uwh/icons/icon-192.png',
    },
    {
      id: 'mister-cim10',
      name: 'Mister CIM-10',
      description:
        'Aide à la cotation CIM-10 dans le navigateur (export TXT/CSV/PDF).',
      maturity: 'stable',
      category: 'sante',
      backend: 'local',
      platform: 'web',
      configs: [
        'components.css',
        'csv',
        'download',
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/bottom-nav',
        'react/confirm-dialog',
        'react/i18n',
        'react/labels',
        'react/observability',
        'react/theme-toggle',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-cim10',
      appUrl: 'https://mister-guiiug.github.io/mister-cim10/',
      iconUrl: 'https://mister-guiiug.github.io/mister-cim10/favicon.svg',
    },
    {
      id: 'mister-footcoach',
      name: 'Mister Footcoach',
      description:
        "Gestion d'équipes de foot : compositions, statistiques, entraînements.",
      maturity: 'alpha',
      category: 'sport',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'download',
        'eslint-react',
        'ical',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/badge',
        'react/bottom-nav',
        'react/button',
        'react/confirm-dialog',
        'react/empty-state',
        'react/i18n',
        'react/icons-context',
        'react/icons-lucide',
        'react/observability',
        'react/sheet',
        'react/toast',
        'react/update-prompt-banner',
        'react/use-update-prompt',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-footcoach',
      appUrl: 'https://mister-guiiug.github.io/mister-footcoach/',
      iconUrl: 'https://mister-guiiug.github.io/mister-footcoach/logo.svg',
    },
    {
      id: 'mister-puzzle',
      name: 'Mister Puzzle',
      description: 'Suivi collaboratif de progression de puzzle en temps réel.',
      maturity: 'stable',
      category: 'jeux',
      backend: 'firebase',
      platform: 'web',
      configs: [
        'components.css',
        'eslint-react',
        'image',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/confirm-dialog',
        'react/observability',
        'react/update-prompt-banner',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
        'web-vitals',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-puzzle',
      appUrl: 'https://mister-guiiug.github.io/mister-puzzle/',
      iconUrl: 'https://mister-guiiug.github.io/mister-puzzle/favicon.svg',
    },
    {
      id: 'miss-ticket-pwa',
      name: 'Miss Ticket',
      description: "Télécommande PWA pour l'application desktop Miss Ticket.",
      maturity: 'alpha',
      category: 'outils',
      backend: 'firebase',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'eslint-react',
        'lint-staged',
        'pairing',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/i18n',
        'react/icons-lucide',
        'react/observability',
        'react/use-online',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-ticket-pwa',
      appUrl: 'https://mister-guiiug.github.io/miss-ticket-pwa/',
      iconUrl: 'https://mister-guiiug.github.io/miss-ticket-pwa/favicon.svg',
    },
    {
      id: 'mister-doc',
      name: 'Mister Doc',
      description:
        'Planning de gardes de médecins synchronisé : vue mensuelle, compteurs week-end et heures.',
      maturity: 'stable',
      category: 'sante',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'components.css',
        'eslint-react',
        'lint-staged',
        'pdf',
        'prettier',
        'push',
        'react',
        'react/bottom-nav',
        'react/button',
        'react/confirm-dialog',
        'react/empty-state',
        'react/field',
        'react/i18n',
        'react/icons-context',
        'react/icons-lucide',
        'react/labels',
        'react/observability',
        'react/sheet',
        'react/skeleton',
        'react/theme-provider',
        'react/toast',
        'react/update-prompt-banner',
        'react/use-update-prompt',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
        'xlsx',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-doc',
      appUrl: 'https://mister-guiiug.github.io/mister-doc/',
      iconUrl: 'https://mister-guiiug.github.io/mister-doc/favicon.svg',
    },
    {
      id: 'miss-lookhouse',
      name: 'Miss Lookhouse',
      description:
        'Veille immobilière : multi-sources, anti-doublons, historique des prix, scoring explicable.',
      maturity: 'beta',
      category: 'outils',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'eslint-react',
        'format',
        'geo',
        'prettier',
        'react/app-footer',
        'react/badge',
        'react/bottom-nav',
        'react/icons-context',
        'react/sparkline',
        'react/theme-provider',
        'react/theme-toggle',
        'storage',
        'supabase-client',
        'sync-queue',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-lookhouse',
      appUrl: 'https://mister-guiiug.github.io/miss-lookhouse/',
      iconUrl: 'https://mister-guiiug.github.io/miss-lookhouse/favicon.svg',
    },
    {
      id: 'miss-badminton',
      name: 'Miss Badminton',
      description: 'Suivi de scores et statistiques de badminton.',
      maturity: 'stable',
      category: 'sport',
      backend: 'local',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'download',
        'eslint-react',
        'idb',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/confirm-dialog',
        'react/observability',
        'react/sheet',
        'react/sparkline',
        'react/use-online',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-badminton',
      appUrl: 'https://mister-guiiug.github.io/miss-badminton/',
      iconUrl: 'https://mister-guiiug.github.io/miss-badminton/favicon.svg',
    },
    {
      id: 'miss-dice',
      name: 'Miss Dice',
      description: 'Lanceur de dé à 6 faces, 100 % hors ligne, installable.',
      maturity: 'stable',
      category: 'jeux',
      backend: 'local',
      platform: 'web',
      configs: [
        'apps-catalog',
        'commitlint',
        'download',
        'eslint-react',
        'lint-staged',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'react',
        'react/observability',
        'react/use-wake-lock',
        'share',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-dice',
      appUrl: 'https://mister-guiiug.github.io/miss-dice/',
      iconUrl: 'https://mister-guiiug.github.io/miss-dice/favicon.svg',
    },
    {
      id: 'miss-supaboss',
      name: 'Miss Supaboss',
      description:
        'Pilotage multi-comptes Supabase Free : pause/restore, quotas, démos.',
      maturity: 'beta',
      category: 'dev',
      backend: 'api',
      platform: 'web',
      configs: [
        'apps-catalog',
        'commitlint',
        'components.css',
        'eslint-react',
        'format',
        'lint-staged',
        'playwright-base',
        'prettier',
        'react',
        'react/badge',
        'react/bottom-nav',
        'react/confirm-dialog',
        'react/empty-state',
        'react/error-boundary',
        'react/i18n',
        'react/icons-context',
        'react/observability',
        'react/skeleton',
        'react/toast',
        'react/update-prompt-banner',
        'react/use-online',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-supaboss',
      appUrl: 'https://mister-guiiug.github.io/miss-supaboss/',
      iconUrl: 'https://mister-guiiug.github.io/miss-supaboss/favicon.svg',
    },
    {
      id: 'miss-supatool',
      name: 'Miss Supatool',
      description:
        "Migration d'un projet Supabase vers un autre : structure, données et fichiers.",
      maturity: 'beta',
      category: 'dev',
      backend: 'api',
      platform: 'web',
      configs: [
        'components.css',
        'download',
        'eslint-react',
        'format',
        'prettier',
        'react/app-header',
        'react/badge',
        'react/bottom-nav',
        'react/button',
        'react/card',
        'react/confirm-dialog',
        'react/empty-state',
        'react/family-apps',
        'react/field',
        'react/observability',
        'react/page-container',
        'react/segmented-control',
        'react/stat',
        'react/theme-provider',
        'react/theme-toggle',
        'react/toast',
        'react/update-prompt-banner',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/miss-supatool',
      appUrl: 'https://mister-guiiug.github.io/miss-supatool/',
      iconUrl: 'https://mister-guiiug.github.io/miss-supatool/favicon.svg',
    },
    {
      id: 'mister-molkky',
      name: 'Mister Mölkky',
      description:
        'Compteur de scores pour parties de Mölkky (multi-appareils).',
      maturity: 'stable',
      category: 'jeux',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'download',
        'eslint-react',
        'lint-staged',
        'pairing',
        'playwright-a11y',
        'playwright-base',
        'prettier',
        'qr',
        'react',
        'react/confirm-dialog',
        'react/icons-context',
        'react/icons-lucide',
        'react/labels',
        'react/observability',
        'react/sheet',
        'react/skeleton',
        'react/sparkline',
        'react/use-online',
        'react/use-qr-scanner',
        'react/use-wake-lock',
        'share',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-molkky',
      appUrl: 'https://mister-guiiug.github.io/mister-molkky/',
      iconUrl: 'https://mister-guiiug.github.io/mister-molkky/logo.png',
    },
    {
      id: 'mister-qowa',
      name: 'Mister Qowa',
      description:
        "Quiz interactif en temps réel : l'animateur pilote, les joueurs répondent.",
      maturity: 'stable',
      category: 'jeux',
      backend: 'firebase',
      platform: 'web',
      configs: [
        'apps-catalog',
        'components.css',
        'csv',
        'download',
        'eslint-react',
        'pairing',
        'playwright-base',
        'qr',
        'react/app-footer',
        'react/app-updates',
        'react/confirm-dialog',
        'react/error-boundary',
        'react/use-install-prompt',
        'share',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vitest-base',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-qowa',
      appUrl: 'https://mister-guiiug.github.io/mister-qowa/',
      iconUrl: 'https://mister-guiiug.github.io/mister-qowa/icons/icon.svg',
    },
    {
      id: 'mister-family-map',
      name: 'Mister Family Map',
      description:
        'Idées de sorties en famille : carte collaborative, agenda et retours d’expérience.',
      maturity: 'beta',
      category: 'loisirs',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'commitlint',
        'components.css',
        'correlation',
        'eslint-react',
        'geo',
        'lint-staged',
        'logger',
        'map',
        'map/maplibre',
        'playwright-a11y',
        'playwright-base',
        'prefetch',
        'prettier',
        'react',
        'react/app-version',
        'react/observability',
        'react/share-button',
        'react/update-prompt-banner',
        'react/version',
        'realtime',
        'realtime/local',
        'storage',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'vite-csp',
        'vite-pwa-base',
        'vite-version',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-family-map',
      appUrl: 'https://mister-guiiug.github.io/mister-family-map/',
      iconUrl: 'https://mister-guiiug.github.io/mister-family-map/favicon.svg',
    },
    {
      id: 'mister-miss-koh',
      name: 'Mister & miss Koh',
      description:
        "Suivi d'une saison d'aventure : candidats, épisodes, épreuves, conseils et votes. Non officiel.",
      maturity: 'beta',
      category: 'loisirs',
      backend: 'supabase',
      platform: 'web',
      configs: [
        'backend',
        'commitlint',
        'components.css',
        'eslint-react',
        'format',
        'lint-staged',
        'prettier',
        'react/app-footer',
        'react/app-header',
        'react/app-updates',
        'react/badge',
        'react/bottom-nav',
        'react/button',
        'react/card',
        'react/empty-state',
        'react/error-boundary',
        'react/icons-context',
        'react/icons-lucide',
        'react/labels',
        'react/page-container',
        'react/rive',
        'react/theme-provider',
        'react/use-media-query',
        'react/use-online',
        'storage',
        'supabase-client',
        'tailwind-preset.css',
        'tsconfig-app-react',
        'tsconfig-node',
        'versioned-store',
        'vite-csp',
        'vite-pwa-base',
        'vitest-base',
        'vitest-setup',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-miss-koh',
      appUrl: 'https://mister-guiiug.github.io/mister-miss-koh/',
      iconUrl: 'https://mister-guiiug.github.io/mister-miss-koh/favicon.svg',
    },
    {
      id: 'mister-quota',
      name: 'Mister Quota',
      description:
        'Suivi de consommation des services IA (application desktop).',
      maturity: 'alpha',
      category: 'dev',
      platform: 'desktop',
      configs: [
        'components.css',
        'format',
        'prettier',
        'react/confirm-dialog',
        'react/error-boundary',
        'react/toast',
      ],
      repoUrl: 'https://github.com/mister-guiiug/mister-quota',
      appUrl: 'https://github.com/mister-guiiug/mister-quota',
      iconUrl: null,
    },
  ],
};
